name: ivanbatistamoreno206660-services
services:
  postgres:
    container_name: postgres
    image: postgres:17.4
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      TZ: "America/Cuiaba"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    volumes:
      - minio_data:/data
    environment:
      TZ: "America/Cuiaba"
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"

  minio-init:
    container_name: minio-init
    image: minio/mc:latest
    depends_on:
      - minio
    restart: "no"
    volumes:
      - ./minio/cors.json:/tmp/cors.json:ro
    environment:
      MINIO_USER: ${MINIO_USER}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 $$MINIO_USER $$MINIO_PASSWORD; do
        echo 'Aguardando MinIO...';
        sleep 2;
      done;
      mc mb --ignore-existing local/$$MINIO_BUCKET_NAME;
      mc cors set local/$$MINIO_BUCKET_NAME /tmp/cors.json;
      "

  backend-api:
    container_name: backend-api
    image: ibmoreno/backend-api:latest
    build: .
    depends_on:
      - postgres
      - minio
      - minio-init
    ports:
      - "8080:8080"
    environment:
      TZ: "America/Cuiaba"
      SERVER_PORT: 8080
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      JDBC_POSTGRES_URL: ${POSTGRES_URL}
      JDBC_POSTGRES_USER: ${POSTGRES_USER}
      JDBC_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRINGDOC_API_DOCS_ENABLED: true
      SPRINGDOC_SWAGGER_UI_ENABLED: true

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
